### ISSUE TITLE
Update `elmish`

### ISSUE THREAD

**Issue by fsoikin** [purescript/registry#159]
```json
{
  "name": "elmish",
  "ref": "v0.9.3",
  "compiler": "0.15.4"
}
```

**Comment by fsoikin** [comment]
Hmmm, something's not right. Checking `packages.dhall` from the [latest package set](https://github.com/purescript/package-sets/releases/tag/psc-0.15.7-20230126), the version there is still 0.8.2

**Comment by thomashoneyman** [comment]
The automatic package set updates may have missed this or it did not compile with something else. Try submitting a package set update with all the packages you think should be at different versions and it will either update or tell you why the update can’t go through!

**Comment by fsoikin** [comment]
Ok, package set update helped, thank you for the pointer @thomashoneyman 

Perhaps it would be worth it to add this advice to the "version already exists" message that the bot posts?

**Comment by f-f** [comment]
@fsoikin the two things are unrelated: the error from the bot is just telling you that the version that you tried to upload can't be published because one is already there.

The fact that it didn't end up in the package set is orthogonal, and not a concern that should be mixed into the publishing pipeline.
The misunderstanding likely stems from the fact that not seeing the version included in the package set, you thought that it was not uploaded. This will be mitigated by the new publishing process coming soon.
In the meantime, if you want to look up if a version was published or not, you can open [the package's metadata file](https://github.com/purescript/registry/blob/main/metadata/elmish.json) or use Spago Next to query the registry, with `spago registry info elmish`

**Comment by fsoikin** [comment]
I was coming from the perspective of discoverability. If I see that error for the first time, how do I even start to investigate? Maybe what you just wrote @f-f could be added? Or a link somewhere?

**Comment by thomashoneyman** [comment]
Yea, I think the message could be improved to say "This version already exists in the registry, here are links to its metadata file and tarball in storage."

**Comment by f-f** [comment]
I am perhaps failing to understand how the error is confusing: it's literally telling you "the version that you asking to publish already exists: it was published on this date, etc".
There's no solution for this other than publishing a new version, and I do not think that suggesting things like "maybe you forgot to add this to the package set?" is going to make it any clearer? The two things are not related.

A key point in all of this is: it's a temporary situation! Right now we have an automated thing that automatically publishes versions for registered packages, which is probably what published the version that you were trying to publish today. This is only happening to ease the transition to the new registry, and will not be on in the future. And publishing will not happen by opening an issue, but right from your terminal, giving you some more contextual information about what's happening.

**Comment by fsoikin** [comment]
Ok, I will concede that the temporary nature of the situation makes the issue moot. Anyway, I didn't mean to start a big discussion about this, just offered a suggestion.

**Comment by MonoidMusician** [comment]
I think it's reasonable to expect more information and context from the error messages here, and that is something I want to work in improving in particular. And build some tooling for users to debug issues, since I've had weeks of “fun” with that already :D

> Right now we have an automated thing that automatically publishes versions for registered packages

I understand that automatically publishing legacy packages is temporary, but we'll keep doing the automated package sets right? Which is the issue here, the automated package set process isn't transparent enough. It makes sense that users would believe that the package wasn't registered if it's not in the package set, when it might not be in the package set for other reasons that we should do our best to surface.

In fact I think it's likely that in the period when the registry wasn't exactly working and we were waiting for the big rewrites to fix things, the package set updater missed some additions and never went back to pick them up. I'm assuming the package set updater only looks at packages from the last 24 hours or something? I haven't had a chance to look at the actual code yet. Anyways, elmish 0.9.3 was imported to the registry on January 4th so that sounds like the right timeframe for those issues.

**Comment by thomashoneyman** [comment]
> I'm assuming the package set updater only looks at packages from the last 24 hours or something?

That's right. You can run the package set updater script locally and set the time frame to much longer if you want to try and sweep packages that may have been missed during downtime.
