### ISSUE TITLE
Remove bigintegers

### ISSUE THREAD

**Issue by Ebmtranceboy** [purescript/registry#222]
```json
{
  "packages": {
    "bigintegers": "null"
  }
}
```

**Comment by Ebmtranceboy** [comment]
{
  "packages": {
    "bigintegers": null
  }
}

**Comment by f-f** [comment]
@Ebmtranceboy what's the reason for dropping this package from the set?

**Comment by Ebmtranceboy** [comment]
I didn't notice that a similar package, js-bigints, had already been submitted by sigma-andex, and I'd prefer not to contribute to more redundancy.

**Comment by f-f** [comment]
Ah that makes sense. I'll remove it then! 
A few things to keep in mind:
- the package is not removed from the registry, just from the package set (because removing it from the registry might break people's builds)
- if you ever publish a new version then it will reappear in the package set. If you wish to be able to push new versions and not have the package in the set, then we'd need to implement some flag to prevent a package from being added automatically. Please open a ticket over at `registry-dev` if you'd like this behaviour.

**Comment by f-f** [comment]
```
{
  "packages": {
    "bigintegers": null
  }
}
```

**Comment by Ebmtranceboy** [comment]
OK, got it. Thanks

**Comment by Ebmtranceboy** [comment]
@f-f Is it ok to close this issue ?
