### ISSUE TITLE
Add halogen-bootstrap5

### ISSUE THREAD

**Issue by f-f** [purescript/registry#28]
From #27

```
{
  "newPackageLocation": {
    "githubOwner": "tonicebrian",
    "githubRepo": "purescript-halogen-bootstrap5"
  },
  "newRef": "7e0fd4a8d2e1cfa2f370b9d99edfcad467fa5a62",
  "packageName": "halogen-bootstrap5",
  "buildPlan": { "compiler": "0.15.4" }
}
```

**Comment by thomashoneyman** [comment]
https://github.com/purescript/registry/actions/runs/3228151534

Looks like we need to adjust how we fetch locations, as that's a valid ref but we are failing to clone it. That said, publishing this package at that ref will not work anyways, because this is a legacy package (there is no `purs.json` file). Legacy packages must always have a Git tag corresponding with a registry version (ie. a tag `1.0.0`)

**Comment by tonicebrian** [comment]
@thomashoneyman  I'm following instructions from here https://discourse.purescript.org/t/how-i-publish-a-purescript-package/2482 

Please let me know how should I proceed with the new procedure.

**Comment by thomashoneyman** [comment]
#29 is all you need to know! Your docs are published to Pursuit and the package will be added to the package sets tonight.
