### ISSUE TITLE
Update purescript-bound

### ISSUE THREAD

**Issue by benjamin-hodgson** [purescript/registry#302]
```json
{
  "name": "bound",
  "ref": "v0.6.0",
  "compiler": "0.15.9"
}
```

**Comment by benjamin-hodgson** [comment]
```json
{
  "name": "bound",
  "ref": "v0.6.0",
  "compiler": "0.15.9"
}
```

**Comment by stephen-smith** [comment]
I know this is closed, and probably the wrong place to ask, but how do I figure out which package-set I need to use in order to depend on this package (`bound`), I tried doing an `upgrade-set` and then removing my local fork from my packages.dhall, but the build failed saying the package was missing.

Trying to use psc-0.15.15-20240320 package-set AND purescript-bound.

Would be nice if Pursuit told me which package-set(s) included the version of the package it is showing me the documentation for. :/

**Comment by f-f** [comment]
@stephen-smith you're right - there are no facilities for this right now. This is something I wanted to implement in Spago since a long time, and we're actually most of the way there: we store the info, and it just need to be printed out. I opened https://github.com/purescript/spago/issues/1218 to track this.
