### ISSUE TITLE
Update  yoga-json

### ISSUE THREAD

**Issue by sigma-andex** [purescript/registry#38]
```json
{
  "name": "yoga-json",
  "ref": "v4.0.0",
  "compiler": "0.15.4"
}
```

**Comment by sigma-andex** [comment]
Uhmmm 🧐

**Comment by f-f** [comment]
No worries, this means something's broken in our code 😄

**Comment by sigma-andex** [comment]
haha ok, was already scared I screwed it up somehow :D

**Comment by f-f** [comment]
```
{
  "name": "yoga-json",
  "ref": "v4.0.0",
  "compiler": "0.15.4"
}
```

**Comment by sigma-andex** [comment]
Uhm is this maybe a caching issue?

**Comment by f-f** [comment]
No, I suspect this is because you updated your Spago file to include the bigint library but not the bower file - they should be in sync for the time being

**Comment by thomashoneyman** [comment]
This issue is happening because when a legacy project has both a `bower.json` and `spago.dhall` file, it uses the Bower file as the source of truth on the dependency names. That's because people often include test dependencies in their spago files. In this case, `yoga-json@4.0.0` does not list `js-bigints` in its dependencies list.

**Comment by sigma-andex** [comment]
ok got it, will update the bower file then. thx
